[package]
name    = "sqllogictest-test"
version = "0.4.0"
edition = "2021"
default-run = "sqllogictest-test"

[dependencies]
clap            = { version = "4" }
"kite_sql"      = { path = "../..", default-features = false, features = ["copy", "decimal", "lmdb", "macros", "orm", "parser", "spill", "time"] }
glob            = { version = "0.3" }
sqllogictest    = { version = "0.29.1" }
tempfile        = { version = "3.10" }
